### ISSUE TITLE
Superfence warning with pygments 2.20.0

### ISSUE THREAD

**Issue by afroch** [pygments/pygments#3077]
Hi!

We are using `mkdocs` to produce our documentation, which includes a bit of code. We usually don't fix the pygments version, but with 2.20.0, we get the following warning (which kills our strict build of our docs):

```bash
WARNING -  mkdocs_autorefs: software/tutorials/tutorial-upp.md: Could not find cross-reference target ':'
WARNING -  mkdocs_autorefs: software/tutorials/tutorial-upp.md: Could not find cross-reference target '"pt_btagJes"'
WARNING -  mkdocs_autorefs: software/tutorials/tutorial-upp.md: Could not find cross-reference target '"pt_btagJes"'
WARNING -  mkdocs_autorefs: software/tutorials/tutorial-upp.md: Could not find cross-reference target '"pt_btagJes"'
```

The code markdown is the following:

```markdown
??? warning "Solution: Plot Input Distributions"

    You can plot for example the $p_\text{T}$ distribution with the following snippet.
    Note that you have to replace `<path_to_ttbar_h5_file>` with the actual path to the ttbar file you downloaded.

    ```python
    import h5py
    from puma import Histogram, HistogramPlot

    ttbar_filepath = "<path_to_ttbar_h5_file>"

    # load the jets dataset from the h5 file
    with h5py.File(ttbar_filepath, "r") as h5file:
        jets = h5file["jets"][:]

    # defining boolean arrays to select the different flavour classes
    is_light = jets["HadronConeExclTruthLabelID"] == 0
    is_c = jets["HadronConeExclTruthLabelID"] == 4
    is_b = jets["HadronConeExclTruthLabelID"] == 5

    # initialise the plot
    pt_plot = HistogramPlot(
        bins_range=(0, 250_000),
        xlabel="$p_T$ [MeV]",
        ylabel="Normalised number of jets",
    )

    # add the histograms
    pt_plot.add(Histogram(jets[is_light]["pt_btagJes"], flavour="ujets"))
    pt_plot.add(Histogram(jets[is_c]["pt_btagJes"], flavour="cjets"))
    pt_plot.add(Histogram(jets[is_b]["pt_btagJes"], flavour="bjets"))


    pt_plot.draw()
    pt_plot.savefig("tutorial_histogram_pT.png")
    ```
```

It seems that somehow the admonition + superfence breaks now mkdocs_autorefs.

The reason why I open the issue here is that when I run the same thing with pygments 2.19.2, everything works perfectly fine. The moment I switch to 2.20.0, it produces the warning as described at the top.

I fixed for now the version of pygments to 2.19.2, but I thought it might be helpful to post this here.

Cheers

**Comment by Granjow** [comment]
I also had to version-pin 2.19.2 because 2.20.0 breaks Markdown formatting completely. 

Here a more or less minimum example.

[pygments-example.tar.gz](https://github.com/user-attachments/files/26811944/pygments-example.tar.gz)

To reproduce:

```bash
python -m venv venv
. venv/bin/activate
pip install -r requirements.txt
mkdocs build
```

When changing pyygments to 2.19.2, the output renders fine, with 2.20.0, formatting is broken.

**Comment by pellepim** [comment]
Claude and I traced this to a specific regression in `HtmlFormatter.__init__`.

**The breaking change**

In 2.20.0, `formatters/html.py:434` was added/changed to:

```python
self.filename = html.escape(self._decodeifneeded(options.get('filename', '')))
```

The default value `''` only applies when `filename` is absent from `options`. When a caller passes `filename=None` explicitly, `options.get('filename', '')` returns `None`, and `html.escape(None)` raises:

```
AttributeError: 'NoneType' object has no attribute 'replace'
```

I use zensical rather than mkdocs, but I am fairly sure that this is the same thing. superfences swallows the exception silently and the raw backtick markup passes through to the Markdown block parser, which renders it as inline `<code>` with the language hint visible as text.

**Steps to reproduce Reproduction**

```
from pygments.formatters.html import HtmlFormatter

# Works in 2.19.2, crashes in 2.20.0
HtmlFormatter(filename=None)
```

**Suggested fix**

```python
self.filename = html.escape(self._decodeifneeded(options.get('filename') or ''))
```

This handles both the absent key and explicit `None` cases.

I've opened a PR for this purpose below, see below.

**Comment by styx0x6** [comment]
Hi all,

Sorry to raise again this topic, just read it now, but I think there is an overlap between #3076 and #3077, and their resolutions.

@pellepim, the solution in PR #3090 wasn't merged at the time of your analysis. So, regarding PR #3016, ` or '')` in `self.filename = html.escape(self._decodeifneeded(options.get('filename') or ''))` will work but is redondant to the `html_escape` solution and respond only to the filename issue, not to other escaped fields. Also, it will not handle other type of values, like `int` (see lepture/shibuya/issues/113). I did the same mistake in #3078, amended by PR #3090 to address it.

> I use zensical rather than mkdocs, but I am fairly sure that this is the same thing. superfences swallows the exception silently and the raw backtick markup passes through to the Markdown block parser, which renders it as inline < code > with the language hint visible as text.

Correct and a good catch, didn't saw this relationship.

So #3090 will handle it in this case.

**Proposals to fix the redondant fix** @Anteru , @birkenfeld :
- Revert commit b6f6dab78e13652741d5e5811b4256b4dcb5fcd8. Will also remove the test.
- A new PR to remove ` or '')` on escaped filename field. We can let the test which is correct.

Best regards.
